function pug_escape(e){var a=""+e,t=pug_match_html.exec(a);if(!t)return e;var r,c,n,s="";for(r=t.index,c=0;r<a.length;r++){switch(a.charCodeAt(r)){case 34:n="&quot;";break;case 38:n="&amp;";break;case 60:n="&lt;";break;case 62:n="&gt;";break;default:continue}c!==r&&(s+=a.substring(c,r)),c=r+1,s+=n}return c!==r?s+a.substring(c,r):s}
var pug_match_html=/["&<>]/;
function pug_rethrow(n,e,r,t){if(!(n instanceof Error))throw n;if(!("undefined"==typeof window&&e||t))throw n.message+=" on line "+r,n;try{t=t||require("fs").readFileSync(e,"utf8")}catch(e){pug_rethrow(n,null,r)}var i=3,a=t.split("\n"),o=Math.max(r-i,0),h=Math.min(a.length,r+i),i=a.slice(o,h).map(function(n,e){var t=e+o+1;return(t==r?"  > ":"    ")+t+"| "+n}).join("\n");throw n.path=e,n.message=(e||"Pug")+":"+r+"\n"+i+"\n\n"+n.message,n}function template(locals) {var pug_html = "", pug_mixins = {}, pug_interp;var pug_debug_filename, pug_debug_line;try {var pug_debug_sources = {"error.pug":"extends layout\n\nblock content\n  h1= message\n  h2= error.status\n  pre #{error.stack}\n","layout.pug":"doctype html\nhtml\n  head\n    title= title\n    link(rel='stylesheet', href='\u002Fstylesheets\u002Fstyle.css')\n  body\n    block content\n"};
;var locals_for_with = (locals || {});(function (error, message, title) {;pug_debug_line = 1;pug_debug_filename = "layout.pug";
pug_html = pug_html + "\u003C!DOCTYPE html\u003E";
;pug_debug_line = 2;pug_debug_filename = "layout.pug";
pug_html = pug_html + "\u003Chtml\u003E";
;pug_debug_line = 3;pug_debug_filename = "layout.pug";
pug_html = pug_html + "\u003Chead\u003E";
;pug_debug_line = 4;pug_debug_filename = "layout.pug";
pug_html = pug_html + "\u003Ctitle\u003E";
;pug_debug_line = 4;pug_debug_filename = "layout.pug";
pug_html = pug_html + (pug_escape(null == (pug_interp = title) ? "" : pug_interp)) + "\u003C\u002Ftitle\u003E";
;pug_debug_line = 5;pug_debug_filename = "layout.pug";
pug_html = pug_html + "\u003Clink rel=\"stylesheet\" href=\"\u002Fstylesheets\u002Fstyle.css\"\u003E\u003C\u002Fhead\u003E";
;pug_debug_line = 6;pug_debug_filename = "layout.pug";
pug_html = pug_html + "\u003Cbody\u003E";
;pug_debug_line = 7;pug_debug_filename = "layout.pug";
;pug_debug_line = 4;pug_debug_filename = "error.pug";
pug_html = pug_html + "\u003Ch1\u003E";
;pug_debug_line = 4;pug_debug_filename = "error.pug";
pug_html = pug_html + (pug_escape(null == (pug_interp = message) ? "" : pug_interp)) + "\u003C\u002Fh1\u003E";
;pug_debug_line = 5;pug_debug_filename = "error.pug";
pug_html = pug_html + "\u003Ch2\u003E";
;pug_debug_line = 5;pug_debug_filename = "error.pug";
pug_html = pug_html + (pug_escape(null == (pug_interp = error.status) ? "" : pug_interp)) + "\u003C\u002Fh2\u003E";
;pug_debug_line = 6;pug_debug_filename = "error.pug";
pug_html = pug_html + "\u003Cpre\u003E";
;pug_debug_line = 6;pug_debug_filename = "error.pug";
pug_html = pug_html + (pug_escape(null == (pug_interp = error.stack) ? "" : pug_interp)) + "\u003C\u002Fpre\u003E\u003C\u002Fbody\u003E\u003C\u002Fhtml\u003E";}.call(this,"error" in locals_for_with?locals_for_with.error:typeof error!=="undefined"?error:undefined,"message" in locals_for_with?locals_for_with.message:typeof message!=="undefined"?message:undefined,"title" in locals_for_with?locals_for_with.title:typeof title!=="undefined"?title:undefined));} catch (err) {pug_rethrow(err, pug_debug_filename, pug_debug_line, pug_debug_sources[pug_debug_filename]);};return pug_html;}